#!/bin/bash -eu
#
# Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

normal_case=$1
small_case=$(echo "$1" | tr '[:upper:]' '[:lower:]')

sed -i '' -e "s/sampleprovider/$small_case/g" app/controller/cmi-plugin.go
sed -i '' -e "s/sampleprovider/$small_case/g" pkg/sampleprovider/plugin.go
sed -i '' -e "s/sampleprovider/$small_case/g" pkg/sampleprovider/identity_server.go
sed -i '' -e "s/sampleprovider/$small_case/g" pkg/sampleprovider/machine_server.go
sed -i '' -e "s/SampleProvider/$normal_case/g" pkg/sampleprovider/machine_server.go
sed -i '' -e "s/sampleprovider/$small_case/g" Makefile
sed -i '' -e "s/sampleprovider/$small_case/g" README.md
sed -i '' -e "s/SampleProvider/$normal_case/g" pkg/sampleprovider/apis/provider_spec.go

sed -i '' -e "1 s/sampleprovider/$small_case/" go.mod
sed -i '' -e "s/sampleprovider/$small_case/g" CODEOWNERS
sed -i '' -e "s/sampleprovider/$small_case/g" NOTICE.md
sed -i '' -e "s/SampleProvider/$normal_case/g" README.md

sed -i '' -e "s/SampleProvider/$normal_case/g" hack/rename-provider
sed -i '' -e "s/sampleprovider/$small_case/g" hack/rename-provider

mv pkg/sampleprovider pkg/$small_case

echo "Renamed provider SampleProvider to $normal_case."
echo "PLEASE Update CODEOWNERS file to reflect relevant owners"
