#!/bin/bash -eu
#
# Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

normal_case=$1
small_case=$(echo "$1" | tr '[:upper:]' '[:lower:]')

sed -i '' "s/sampleprovider/$small_case/g" app/controller/main.go
sed -i '' "s/sampleprovider/$small_case/g" pkg/sampleprovider/driver.go
sed -i '' "s/sampleprovider/$small_case/g" pkg/sampleprovider/machineserver.go
sed -i '' "s/sampleprovider/$small_case/g" Makefile
sed -i '' "s/sampleprovider/$small_case/g" README.md
sed -i '' "s/SampleProvider/$normal_case/g" pkg/sampleprovider/apis/provider-spec.go

sed -i '' "s/SampleProvider/$normal_case/g" hack/rename-provider
sed -i '' "s/sampleprovider/$small_case/g" hack/rename-provider

mv pkg/sampleprovider pkg/$small_case

echo "Rename provider SampleProvider to $normal_case."
echo "Create a new git repository with the name machine-controller-manager-provider-$small_case"
echo "Update origin to point to this newly created repository"

