#!/bin/bash -eu
#
# SPDX-FileCopyrightText: 2019 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

project_name=$1
provider_name=$2
provider_name_small_case=$(echo "$2" | tr '[:upper:]' '[:lower:]')

files=( Dockerfile go.mod cmd/machine-controller/main.go pkg/provider/provider.go pkg/provider/apis/validation/validation.go )

echo -e "Following files will be updated according to the new project name "$project_name" and provider name "$provider_name_small_case":\nREADME.md NOTICE.md ${files[@]}"
while true; do
    read -p "Do you wish to continue? [Yes/No]" yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

for file in "${files[@]}"
do
  sed -i '' -e "s/gardener\/machine-controller-manager-provider-sampleprovider/$project_name\/machine-controller-manager-provider-$provider_name_small_case/g" $file
done

sed -i '' -e "s/sampleprovider/$provider_name_small_case/g" README.md
sed -i '' -e "s/SampleProvider/$provider_name/g" README.md
sed -i '' -e "1 s/sampleprovider/$provider_name_small_case/" NOTICE.md

echo "Rename project from gardener to $project_name."
echo "Please Update CODEOWNERS file to reflect relevant owners"