#!/bin/bash -eu
#
# Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

project_name=$1
provider_name=$2
provider_name_small_case=$(echo "$2" | tr '[:upper:]' '[:lower:]')

files=( Dockerfile go.mod cmd/machine-controller/main.go pkg/provider/provider.go pkg/provider/apis/validation/validation.go )

echo -e "Following files will be updated according to the new project name "$project_name" and provider name "$provider_name_small_case":\nREADME.md NOTICE.md ${files[@]}"
while true; do
    read -p "Do you wish to continue? [Yes/No]" yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

for file in "${files[@]}"
do
  sed -i '' -e "s/gardener\/machine-controller-manager-provider-sampleprovider/$project_name\/machine-controller-manager-provider-$provider_name_small_case/g" $file
done

sed -i '' -e "s/sampleprovider/$provider_name_small_case/g" README.md
sed -i '' -e "s/SampleProvider/$provider_name/g" README.md
sed -i '' -e "1 s/sampleprovider/$provider_name_small_case/" NOTICE.md

echo "Rename project from gardener to $project_name."
echo "Please Update CODEOWNERS file to reflect relevant owners"