name: Integration-Tests
description: |
  Runs Integrationtests using TestMachinery

on:
  push:
    branches:
      - master
      - migrate-to-gha
  workflow_dispatch:

jobs:
  integrationtest:
    permissions:
      id-token: write
      contents: read
    uses: gardener/cc-utils/.github/workflows/run-testmachinery-tests.yaml@master
    with:
      test-command: |
        set -euo pipefail
        .ci/test
